### ISSUE TITLE
TIL 논의

### ISSUE THREAD

**Issue by trigonotis97** [procyon0/TIL#1]
TIL 작성에 대해 
각자 자유롭게 관리하는것은 좋지만 좀더 발전하기위해 
다음 모임에서 TIL 작성규칙에 대한 틀을 자유롭게 논의했으면 합니다.

**Comment by neso4** [comment]
저도 그렇게 생각했습니다. 딱히 정해진 형식이 없다보니 제가 메모장 형식으로 적던 것이 잘못된 것이라고 생각이 들었습니다.

**Comment by trigonotis97** [comment]
네. 저도 룰이 없으니 내용이 중구난방이 되어 잔디 채우기용의 의미 없는 글을 쓰는것 같습니다. 
다음 모임때 각자 아이디어를 내보아요.
