### ISSUE TITLE
TIL 파일 정리 방식에 대해서

### ISSUE THREAD

**Issue by trigonotis97** [procyon0/TIL#2]
TIL문서를 하루씩 나누어 작성하는 것이 아닌 주 단위로 작성해보면 어떨까 합니다.

현재 하루분량을 나누어 TIL파일을 작성하고 있습니다.
최근 제 공부량이 부쩍 나태해진데 비해, 지금의 TIL은 지난 날동안 얼마나 공부했는지 눈으로 확인하기 어려우니 벼락치기식 작성에 급급해 더 나태해지는것 같습니다. 

주 단위로 문서를 나누어 보면 한주동안 열심히 해왔는지 빠르게 확인할 수 있어 편할 것 같습니다. 
일단위 작성, 주단위 작성 모두 장단점이 있을것 같습니다. 다음 모임에서 이에대해 논의해보면 어떨까요?

**Comment by neso4** [comment]
저는 일단 하루씩 작성하는게 낫다고 생각합니다. 저도 지금은 비슷한 상황에 처해 TIL을 채워넣는데 급급할 뿐입니다. 
하지만 이 마저도 하지 않으면 최소한의 긴장감 마저도 잃어 버릴 것 같아 지금의 방침을 고수하는 것이 낫다고 생각합니다.
자세한 의견은 다음주에 오프라인에서 만나서 논의하는게 나을 것  같습니다.

**Comment by trigonotis97** [comment]
네. procyon0 님의 말씀을 들어보니 일일작성이 더 나은것 같아보입니다.
아마 이번 논의에서부터 각자 스타일에 따라 작성방식이 달라질것 같군요.
역시 자세한건 다음 오프라인 모임에서 만나서 논의해봅시다. 좋은 하루 되세요.
